### PR TITLE
Fix fatal on quiz attempts review submission when there are deleted q…

### LINKED ISSUE #1742: Fatal Error on Quiz Attempts with Deleted Questions
### Reproduction Steps

+ HS-172678
+ Create a quiz
+ Have student take the quiz
+ Delete a quiz question after user took quiz
+ grade user's attempt and click submit review

### Expected Behavior

+ It saves.

### Actual Behavior

+ A fatal terror 

### Error Messages / Logs

+ Include any relevant error messages or log files
```
Fatal error: Uncaught Error: Call to a member function get_auto_grade_type() on null in /srv/users/manager/apps/natalie-customfields-test/public/wp-content/plugins/lifterlms/includes/models/model.llms.quiz.attempt.question.php:267 Stack trace: #0 /srv/users/manager/apps/natalie-customfields-test/public/wp-content/plugins/lifterlms/includes/models/model.llms.quiz.attempt.php(664): LLMS_Quiz_Attempt_Question->get_status() #1 /srv/users/manager/apps/natalie-customfields-test/public/wp-content/plugins/lifterlms/includes/models/model.llms.quiz.attempt.php(161): LLMS_Quiz_Attempt->is_auto_gradeable() #2 /srv/users/manager/apps/natalie-customfields-test/public/wp-content/plugins/lifterlms/includes/controllers/class.llms.controller.admin.quiz.attempts.php(115): LLMS_Quiz_Attempt->calculate_grade() #3 /srv/users/manager/apps/natalie-customfields-test/public/wp-content/plugins/lifterlms/includes/controllers/class.llms.controller.admin.quiz.attempts.php(69): LLMS_Controller_Admin_Quiz_Attempts->save_grade(Object(LLMS_Quiz_Attempt)) in /srv/users/manager/apps/natalie-customfields-test/public/wp-content/plugins/lifterlms/includes/models/model.llms.quiz.attempt.question.php on line 267


```

### System and Environment Information

<details>
<summary>System Report</summary>

```
Wordpress
-------------------------------------------

Home Url: https://natalie-customfields-test.myliftersite.com
Site Url: https://natalie-customfields-test.myliftersite.com
Login Url: https://natalie-customfields-test.myliftersite.com/wp-login.php
Version: 5.8
Debug Mode: No
Debug Log: No
Debug Display: Yes
Locale: en_US
Multisite: No
Page For Posts: Not Set
Page On Front: Not Set
Permalink Structure: /%postname%/
Show On Front: posts
Wp Cron: Yes


Settings
-------------------------------------------

Version: 5.2.0
Db Version: 5.2.0
Course Catalog: Course Catalog (#14) [https://natalie-customfields-test.myliftersite.com/courses/]
Membership Catalog: Membership Catalog (#15) [https://natalie-customfields-test.myliftersite.com/memberships/]
Student Dashboard: Dashboard (#17) [https://natalie-customfields-test.myliftersite.com/dashboard/]
Checkout Page: Purchase (#16) [https://natalie-customfields-test.myliftersite.com/purchase/]
Course Catalog Per Page: 9
Course Catalog Sorting: menu_order
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order
Site Membership: Not Set
Courses Endpoint: my-courses
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: redeem-voucher
Autogenerate Username: yes
Password Strength Meter: yes
Minimum Password Strength: strong
Terms Required: no
Terms Page: Not Set
Checkout Names: required
Checkout Address: required
Checkout Phone: optional
Checkout Email Confirmation: yes
Open Registration: yes
Registration Names: required
Registration Address: optional
Registration Phone: hidden
Registration Voucher: optional
Registration Email Confirmation: no
Account Names: required
Account Address: required
Account Phone: optional
Account Email Confirmation: yes
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: no
Country: US
Currency: USD
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: yes
Email From Address: team+sandbox@lifterlms.com
Email From Name: A LifterLMS Sandbox
Email Footer Text: 
Email Header Image: 
Cert Bg Width: 800
Cert Bg Height: 616
Cert Legacy Compat: no


Constants
-------------------------------------------

LLMS_REMOVE_ALL_DATA: undefined
LLMS_REST_DISABLE: undefined
LLMS_SITE_FEATURE_RECURRING_PAYMENTS: undefined
LLMS_SITE_IS_CLONE: undefined


Gateways
-------------------------------------------

Stripe: Enabled
Stripe Test Mode: Enabled
Stripe Logging: no
Stripe Order: 1
Manual: Disabled
Manual Logging: 
Manual Order: 1


Server
-------------------------------------------

Mysql Version: 5.7.35
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 5000
Php Max Upload Size: 512 MB
Php Memory Limit: 256M
Php Post Max Size: 1024M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 30
Php Version: 7.3.29
Software: Apache/2.4.48 (Unix) OpenSSL/1.1.1
Wp Memory Limit: 256M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36


Theme
-------------------------------------------

Name: Astra
Version: 3.6.4
Themeuri: https://wpastra.com/
Authoruri: https://wpastra.com/about/
Template: 
Child Theme: No
Llms Support: Yes


Plugins
-------------------------------------------

LifterLMS: 5.2.0
LifterLMS Advanced Quizzes: 1.1.1
LifterLMS Custom Fields: 2.0.1
LifterLMS Stripe Payment Gateway: 5.3.2
Loco Translate: 2.5.3
User Switching: 1.5.7


Integrations
-------------------------------------------

BbPress: No
BuddyPress: No


Template Overrides
-------------------------------------------




```

</details>

This issue has be recreated:
+ [X] Locally
+ [X] On a staging site
+ [X] On a production website
+ [X] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)

### PR DESCRIPTION
**Pull request by eri-trabiccolo**
…uestions

## Description
Fixes #1742 

## How has this been tested?
manually

## Types of changes
Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code has been tested.
- [x] My code passes all existing automated tests. 
- [x] My code follows the LifterLMS Coding & Documentation Standards.

### CODE REVIEW

**Comment by thomasplevy** [comment]
@eri-trabiccolo while I appreciate that this fixes the fatal error I feel there's more work to do here before we can call this a successful PR...

It's probably better than a fatal but if we ship this we'll have users in a confused state trying to grade questions they can't see:

Screenshot_2021-08-16_14-34-35

This screenshot is from a quiz attempt that had 3 questions when the student took the quiz but now only has 1.

Grading works and there's no fatal but the data at the top of the screen is confusing given the interface we see now and, additionally, the correct grade cannot be shown here.

This is the result of what I believe is likely several bug fixes we've shipped over the years which all do the same sort of patch: fix the fatal error and move on. 

I'd like to address this properly, although I'm not entirely sure what the solution is. I'm thinking that we should likely either remove questions from the quiz attempt entirely when a question is deleted or retain it but convert it to "deleted" so that the user can *see* what's happened.

EG: instead of skipping it it should still be included but the output on the frontend should *show* that there was a question here, retain the answer, but show the question as "[Deleted]" or something like that...

In this scenario if the grade is "stuck" that is probably *okay* but at the least the user can see why it's stuck or how the grade was a calculated

**Comment by eri-trabiccolo** [comment]
@thomasplevy I agree with you.

> I'd like to address this properly, although I'm not entirely sure what the solution is. I'm thinking that we should likely either remove questions from the quiz attempt entirely when a question is deleted or retain it but convert it to "deleted" so that the user can see what's happened.

I initially wanted to discuss with you about "what to do" but then I opted to just fix the bug as I thought you just wanted an easy fix. I thought that deleting a question from an attempt would possibly retroactively make a quiz passed, and I don't think this is correct. So I would rather not do that.

> EG: instead of skipping it it should still be included but the output on the frontend should show that there was a question here, retain the answer, but show the question as "[Deleted]" or something like that...

Yeah, actually this PR doesn't skip it, the question is not shown because of a skip somewhere else. I will individuate it and replace it with some message showing it's deleted.

> In this scenario if the grade is "stuck" that is probably okay but at the least the user can see why it's stuck or how the grade was a calculated

Yeah.

**Comment by thomasplevy** [comment]
> Yeah, actually this PR doesn't skip it, the question is not shown because of a skip somewhere else. I will individuate it and replace it with some message showing it's deleted.

Sounds good to me thanks

**Comment by eri-trabiccolo** [comment]
Schermata 2021-08-23 alle 16 20 38

**Comment by eri-trabiccolo** [comment]
@thomasplevy this is ready for a review.

**Review by thomasplevy — APPROVED** [review]

**Pull request merged**
