### PR TITLE
Fix conflict with Yoast SEO plugin when creating a quiz in the course…

### LINKED ISSUE #1530: Cannot properly create quizzes when the Yoast SEO plugin is active
### Reproduction Steps

+ Install and activate the Yoast SEO plugin
+ Open the course builder, add a quiz to a lesson
+ Save the changes (or wait for the auto-save if you're not a control-freak :P)

### Expected Behavior

+ I'd expect the changes (quiz addition) to be saved with no errors

### Actual Behavior

+ The quiz is created but only "partially" saved - meaning that not all of its properties have been saved. Plus an error is shown in the builder:
Schermata 2021-02-15 alle 16 49 22

It seems that when saving (I think on post insertion?!) Yoast SEO "expands" the post content (meaning that applies `'the_content'` filter), in this case the quiz content, when the quiz's lesson meta has not been set yet.
But in our template we just assume that this is always set.

### Error Messages / Logs

```
[15-Feb-2021 15:48:48 UTC] PHP Fatal error:  Uncaught Error: Call to a member function get() on bool in /shared/httpd/mywp/wordpress.git/wp-content/plugins/lifterlms/templates/quiz/start-button.php:26

```

### System and Environment Information
(customer's system report)
<details>
<summary>System Report</summary>

```
System Report:
Wordpress
-------------------------------------------

Home Url: [removed]
Site Url: [removed]
Login Url: [removed]/wp-login.php?itsec-hb-token=wplogit
Version: 5.6.1
Debug Mode: No
Debug Log: Yes
Debug Display: No
Locale: en_US
Multisite: No
Page For Posts: Blog (#181) [[removed]/blog/]
Page On Front: Home (#130) [[removed]/]
Permalink Structure: /%postname%/
Show On Front: page
Wp Cron: Yes


Settings
-------------------------------------------

Version: 4.15.0
Db Version: 4.15.0
Course Catalog: Course Catalog (#7) [[removed]/courses/]
Membership Catalog: Membership Catalog (#8) [[removed]/memberships/]
Student Dashboard: Members Dashboard (#60) [[removed]/members-dashboard/]
Checkout Page: Purchase (#9) [[removed]/purchase/]
Course Catalog Per Page: -1
Course Catalog Sorting: title,ASC
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order
Site Membership: Not Set
Courses Endpoint: my-courses
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint:
Autogenerate Username: yes
Password Strength Meter: no
Minimum Password Strength: medium
Terms Required: yes
Terms Page: Disclaimer and Terms of Use (#391) [[removed]/disclaimer-and-terms-of-use/]
Checkout Names: required
Checkout Address: hidden
Checkout Phone: required
Checkout Email Confirmation: yes
Open Registration: no
Registration Names: required
Registration Address: hidden
Registration Phone: required
Registration Voucher: optional
Registration Email Confirmation: yes
Account Names: required
Account Address: hidden
Account Phone: required
Account Email Confirmation: yes
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: yes
Country: US
Currency: USD
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: yes
Email From Address: [removed]
Email From Name: [removed]
Email Footer Text:
Email Header Image: 600
Cert Bg Width: 800
Cert Bg Height: 616
Cert Legacy Compat: no


Constants
-------------------------------------------

LLMS_REMOVE_ALL_DATA: undefined
LLMS_REST_DISABLE: undefined
LLMS_SITE_FEATURE_RECURRING_PAYMENTS: undefined
LLMS_SITE_IS_CLONE: undefined


Gateways
-------------------------------------------

Authorize.Net: Disabled
Authorize.Net Test Mode: Disabled
Authorize.Net Logging:
Authorize.Net Order: 1
PayPal: Enabled
PayPal Test Mode: Disabled
PayPal Logging: yes
PayPal Order: 1
Stripe: Enabled
Stripe Test Mode: Disabled
Stripe Logging: yes
Stripe Order: 1
Manual: Disabled
Manual Logging: no
Manual Order: 1


Server
-------------------------------------------

Mysql Version: 5.5.5
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 5000
Php Max Upload Size: 128 MB
Php Memory Limit: 512M
Php Post Max Size: 256M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 300
Php Version: 7.4.11
Software: Apache
Wp Memory Limit: 40M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36


Theme
-------------------------------------------

Name: WPCrafter LMS
Version: 0.1
Themeuri: https://wpcrafter.com
Authoruri: https://wpcrafter.com
Template: generatepress
Child Theme: Yes
Llms Support: No


Plugins
-------------------------------------------

AnyImage.io Integration: 2.0.0
Classic Editor: 1.6
Cookie Notice & Compliance for GDPR / CCPA: 2.0.2
Duplicate Page: 4.3
Dynamic Visibility for Elementor: 3.0.1
Elementor: 3.1.1
Elementor Addons & Templates - Sizzify Lite: 1.3.2
Elementor Pro: 3.0.10
Google Analytics Dashboard for WP (GADWP): 6.6.0
Google Analytics for WordPress by MonsterInsights: 7.16.0
GP Premium: 1.12.3
Health Check & Troubleshooting: 1.4.5
Imagify: 1.9.14
Insert Google Analytics Id: 1.1.3
iThemes Security Pro: 6.8.3
LifterLMS: 4.15.0
LifterLMS Advanced Quizzes: 1.1.1
LifterLMS Advanced Videos: 1.0.0-beta.13
LifterLMS Assignments: 1.1.11
LifterLMS Authorize.Net Payment Gateway: 1.1.0
LifterLMS ConvertKit: 2.1.0
LifterLMS Custom Fields: 1.0.2
LifterLMS Customizations: 1.0.0
LifterLMS Helper: 3.1.0
LifterLMS MailChimp Add-on: 3.1.2
LifterLMS PayPal Gateway: 1.3.0
LifterLMS Social Learning: 1.3.0
LifterLMS Stripe Payment Gateway: 5.3.1
LifterLMS WPForms: 1.1.1
Mail On Update: 5.4.13
My Custom Functions: 4.48
Nav Menu Roles: 2.0.0
OptinMonster: 2.1.1
Page Templater For Elementor: 1.2.9
PHP Compatibility Checker: 1.5.0
UpdraftPlus - Backup/Restore: 2.16.47.25
Uptime Robot Widget: 1.8.2
User Switching: 1.5.6
WP Content Copy Protection (Lite): 2.0.3
WP Crontrol: 1.9.1
WP File Manager: 7.0
WPForms: 1.6.4.1
WP Mail SMTP: 2.6.0
WP Rocket: 2.10.7
Yoast SEO: 15.8


Integrations
-------------------------------------------

BbPress: No
BuddyPress: No
LifterLMS ConvertKit: No
LifterLMS WPForms: Yes
LifterLMS MailChimp: No
LifterLMS Social Learning: No
Videos: Vimeo: Yes
Videos: Wistia: No
Videos: YouTube: No


Template Overrides
-------------------------------------------

```

</details>

### This issue has been recreated:
+ [x] Locally
+ [ ] On a staging site
+ [x] On a production website
+ [ ] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)

### Related User Information
HS-154941

### PR DESCRIPTION
**Pull request by eri-trabiccolo**
## Description
Fixes #1530 

## How has this been tested?
manually

## Types of changes
plugin conflict fix

## Checklist:
- [x] My code has been tested.
- [x] My code passes all existing automated tests. 
- [x] My code follows the LifterLMS Coding & Documentation Standards.

### CODE REVIEW

**Comment by thomasplevy** [comment]
@eri-trabiccolo do you see any side effects with the updating/creating any other things in the builder?

**Comment by eri-trabiccolo** [comment]
Honestly I don't think so, I've tested it a little bit and cannot see any real problem.
Do you think we should be a little more cautious?

Like for example we can set an LLMS_DOING_AJAX_BUILDER here:
https://github.com/gocodebox/lifterlms/blob/4.15.0/includes/admin/class.llms.admin.builder.php#L326

and early bail here if that's true?
https://github.com/gocodebox/lifterlms/blob/4.15.0/includes/functions/llms-functions-content.php#L26

**Comment by eri-trabiccolo** [comment]
@thomasplevy ^

**Comment by thomasplevy** [comment]
@eri-trabiccolo I'm nervous because the `remove_all_*` functions are pretty aggressive and without having very thorough test coverage here we're taking a "risk" in hoping we know how everything works well enough to not run into any issues.

I'm marginally confident this won't have any negative impact (and will probably prevent some potential future conflicts with other plugins) but without more thorough test coverage to ensure other areas aren't being impacted negatively by this I'm going to be hesitant.

I see two better options:

1) Add thorough test coverage so that we can feel more confident

2) Solve this specific plugin conflict in favor of nuking with the `remove_all_*` filters. 

I think we can do this in the `LLMS_Play_Nice` class and remove only the offending Yoast filters when the builder save is running.

Adding a constant in our builder ajax could be one way to check this. It could also be done by using the same ajax method we use a hook like `wp_ajax_llms_builder` with a priority less than 10. I think.

**Comment by eri-trabiccolo** [comment]
@thomasplevy 
Mmm I see what you mean the thing is that I thought that removing those actions was already our purpose, because of:
https://github.com/gocodebox/lifterlms/blob/4.15.0/includes/admin/class.llms.admin.builder.php#L557-L560

Also, couldn't imagine (find) where in the builder we run those filters, or where we would want to run them.

> Add thorough test coverage so that we can feel more confident

Mmm ok, I guess that the test would be that I can just test that `did_action('the_filter')` and `did_action('the_content')` don't vary from before and after running `LLMS_Admin_Builder::handle_ajax()`...

> Solve this specific plugin conflict in favor of nuking with the remove_all_* filters.

Didn't want to solve this specific conflict only because:
1) It requires us to dive into the plugin logic in the hope we can prevent their stuff
2) I still think that it's something some other plugin could do and we still don't want that.
3) I could even just change the quiz template to prevent this (early bail if no lesson), but I think - not verified yet - a similar thing could happen with the assignment. So I wanted to have a more generic approach.

If you still want the play nice thing ok, let me know.

Sorry wanted to go for a rapid solution :/

**Comment by thomasplevy** [comment]
@eri-trabiccolo if you think this is the best approach I will trust you... I'm just really nervous to ship a change to the builder that isn't thoroughly covered and I'm knee deep in higher priority items so I can't take the time right now to do a very thorough manual review.

I don't think the tests as you described will make me feel better.

What will make me feel better is having integration tests that test the expected post content and title of post types that can be created by the builder 

for example, if we had a test that simulates the creation of a sections, lessons, and quizzes through this ajax method and tests the expected content and title. We can then remove these filters and be assured that removing the filters won't have some negative impact on the expected content.

As I said, I think we're going to be okay here but I'm not terribly positive that's the case. We don't have thorough test coverage so it makes me nervous using these hooks that have potentially far reaching imapact.

And the fact that we're already using them when rendering the page doesn't really make me feel any better. If there's something running while saving that we have come to "expect" to happen (even if we're not fully aware of it) and now it stops running it would cause an issue. 

WHat I mean is that if something is filtered right before the save, then it's possible we're saving the filtered content. This might not be *desired* in all circumstances but my worry is that we've come to rely on it somehow (and we're not aware of it).

Removing a filter that affects *already saved content* (when it's being output) is different than what we're looking at here.

Even if it's the same code the effect is different and -- again -- I'm not confident in our test coverage here and I don't have the time to do a full manual testing of everything to feel confident.

**Comment by eri-trabiccolo** [comment]
@thomasplevy some tests added, what do you think?

**Comment by thomasplevy** [comment]
okay yes... Now, tell me, if you remove the new code (the `remove_all_actions()` functions) does this new test still pass?

If so I approve. Thanks!

**Comment by eri-trabiccolo** [comment]
@thomasplevy 
I treat that case here:
https://github.com/gocodebox/lifterlms/blob/98155ff15d1d10bc9990c66cbe638a665d33d567/tests/phpunit/unit-tests/admin/class-llms-test-admin-builder.php#L343-L354

you know that's equal to this:
https://github.com/gocodebox/lifterlms/blob/98155ff15d1d10bc9990c66cbe638a665d33d567/includes/admin/class.llms.admin.builder.php#L341-L342

so the `'ajax_save'` action without the '`remove_all_actions'` thing.

**Comment by eri-trabiccolo** [comment]
@thomasplevy this is not solved, it's only solved when the manual saving is enabled (new option).
The filters removal should have been done here instead:
https://github.com/gocodebox/lifterlms/blob/4.16.0/includes/admin/class.llms.admin.builder.php#L487

and of course the tests above should be amended to reflect this change.

I'm not going to push another PR now because #1537 fixes this as well, and it's already merged in dev.

**Pull request merged**
