### PR TITLE
Update LifterLMS small grey rocket icon

### LINKED ISSUE #1241: Merge codes button icon uses old logo
### Reproduction Steps

+ Login as admin
+ Visit LifterLMS->Settings->Notifications
+ Edit any notification
+ Look at the Merge Codes button

### Expected Behavior

See the "new" logo as the icon

### Actual Behavior

The old icon is visible

### Error Messages / Logs

n/a

### System and Environment Information

LifterLMS 4.1.0

This issue has be recreated:
+ [x] Locally
+ [x] On a staging site
+ [x] On a production website
+ [x] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

n/a

### PR DESCRIPTION
**Pull request by imknight**
## Description
create a new icon make use of the new brand logo

Fixes #1241

## How has this been tested?
Login as admin
Visit LifterLMS->Settings->Notifications
Edit any notification
Look at the Merge Codes button should be replaced with new logo

## Types of changes
the image /assets/images/lifterlms-rocket-grey.png has been replaced.

### CODE REVIEW

**Comment by thomasplevy** [comment]
Thanks @imknight !

**Comment by thomasplevy** [comment]
@daniel-shuy thanks again for your contribution, you've won a swag item of your choice for submitting 3 or more PRs during Hacktoberfest please reach out to team@lifterlms.com to claim your reward!

**Comment by imknight** [comment]
wrong name ?

**Comment by thomasplevy** [comment]
Sorry, copy pasta. I'm trying. Contact us anyway you know what's going on 👍

**Pull request merged**
