### PR TITLE
Wip/certificate migration

### PR DESCRIPTION
**Pull request by actual-saurabh**
## Description
Draft Class for certificate migration and rollback support for review: https://github.com/actual-saurabh/lifterlms/blob/wip/certificate-migration/includes/modules/certificate-builder/class-llms-certificate-migrator.php

## Checklist:
- [ ] My code has been tested.
- [ ] My code passes all existing automated tests. 
- [ ] My code follows the LifterLMS Coding Standards.

### CODE REVIEW

**Comment by actual-saurabh** [comment]
Added draft class for post table (adds a Build link) and editor modifications. Still need to add metaboxes for migration and rollback.

**Comment by actual-saurabh** [comment]
Added `llms_certificate_is_legacy()` function to differentiate legacy certificates from migrated ones. This will help in context based editor overlays (for legacy vs migrated vs new certificates) and action buttons. Additionally, this will help in conditional frontend templating.

**Comment by actual-saurabh** [comment]
Added a utility class to fetch font-family definitions from the site's homepage to use in tinymce on the builder. This is partially incomplete because it doesn't handle remote stylesheets (CDN, etc) as of now. Will add remote fetching after a bit of testing.

**Comment by thomasplevy** [comment]
@actual-saurabh since we're not actually ready to merge this in yet I'll leave this open until you review my notes and then you can close it (and reopen later when you have something ready to actually merge)

Thanks!

**Comment by thomasplevy** [comment]
@actual-saurabh closing this so since it's not ready to merge

**Pull request closed without merging**
