### PR TITLE
Update minimum supported PHP version to 7.4

### PR DESCRIPTION
**Pull request by pondermatic**
## Description
Updated the minimum supported PHP version from 7.3 to 7.4.

See #1918.

## Checklist:
- [ ] My code has been tested.
- [ ] My code passes all existing automated tests. 
- [ ] My code follows the LifterLMS Coding & Documentation Standards.

### CODE REVIEW

**Comment by thomasplevy** [comment]
At this moment I'm not confident enough people are off 7.3

Let's wait another month or two

We bumped assignments to 7.4 and immediately received complaints from users whou couldn't upgrade. With the 6.0 changes imminent I don't want to create any additional havoc

**Comment by eri-trabiccolo** [comment]
@pondermatic 
from 7.3 to 7.4
:P 

also
@gocodebox/engineering we dropped 7.3 automatic testing https://github.com/gocodebox/.github/blob/a7d6ad273077163c90872c5e8f73e121eef2196d/.github/actions/setup-matrix/src/defaults.json
Shall we re-introduce it until we update the min support version to 7.4? I think so.

**Comment by thomasplevy** [comment]
@eri-trabiccolo I don't want to *reintroduce* official support. What I am suggesting is that we don't bump the official version in the plugin for another little while. My reasoning is that A) We don't currently use any features that aren't available in 7.3 B) As soon as we bump min support, the support team will get lots of emails from unhappy users who can't upgrade and don't understand why and will think that *we've made a mistake*. I want to reduce the number of emails that they have to field about this kind of stuff for a bit longer.

**Comment by eri-trabiccolo** [comment]
@thomasplevy 
I understand and I agree on not bumping the minimum PHP version.
What I'm saying is that if we keep the plugin's PHP supported version set to 7.3 would be better to reintroduce the automatic tests against it to avoid shipping something with any features that aren't available in 7.3. That's exactly what tests agains php version are for, am I wrong?

**Comment by thomasplevy** [comment]
@eri-trabiccolo I am ignoring what is the correct answer but I just don't have the energy or time to add 7.3 back. This wasn't on anyone's radar and now it's more work for me that I don't have time to do. I want us focusing on ensuring 6.0 is working well... Not reintroducing more tested versions because I preemptively removed them and then said "pause" on publicly bumping the version.

**Pull request merged**
