### PR TITLE
Add an option to dismiss admin notifications forever

### LINKED ISSUE #1360: Admin Notices should be able to be dismissed forever
Currently, the `LLMS_Admin_Notices::add_notice()` will redisplay any dismissed notice 7 days after it was dismissed. This default value of 7 days can be overridden with a custom value.

When we wish for something to be permanently dismissed, we add a large value (730 days or 2 years) to make it seem like it's dismissed forever, but this isn't actually what happens.

See related issue #1278 

Ideally the `add_notice()` method should have an option to "dismiss_forever". When a notice is dismissed forever we should record that it has been permantently dismissed the `add_notice()` method should prevent the addition of the notice.

### PR DESCRIPTION
**Pull request by imknight**
## Description
added dismiss_forever option for notice to dismiss and remove

Fixes #1360 

## How has this been tested?
set a notice which will dismiss forever, once hide the notice, check the option has never added back to the option table.

## Types of changes
 New feature (non-breaking change which adds functionality)
## Checklist:
- [X ] My code has been tested.
- [ X] My code passes all existing automated tests
- [X ] My code follows the LifterLMS Coding & Documentation Standards.

### CODE REVIEW

**Review by thomasplevy — COMMENTED** [review]
@imknight I haven't pulled down to test this but I'm pretty sure that this will result in the notice returning again on the next page load in favor of actually dismissing it forever.

Can you confirm that you've tested this with existing notifications and that it works as expected? By that I mean that the "forever" notice never actually returns.

It might be helpful to look at the PR related to #1278 (and the notice in this issue) to see if adding this new option to that value actually has the desired effect.

**Comment by imknight** [comment]
I thought that simply prevent the options to add back will stop the notification appear again.
what's a good way to for me to call out that payment gateway notice?

**Comment by thomasplevy** [comment]
@imknight 

I was on vacation, thanks for your patience!

1) Disable, deactivate, uninstall any and all LifterLMS payment gateways (deactivating might be the only necessary step here, I don't quite remember without digging into it and reading the code)
2) Head into the db and from the `wp_options` table, delete the option with the `option_name` of `llms_notices` (it might actually be `lifterlms_notices` -- We used to not enforce a convention on how things were prefixed and I can't remember off the top of my head which is which.


Best,

**Comment by thomasplevy** [comment]
@imknight closing this since it doesn't currently work. If you wish to continue working on this please reopen or submit an updated PR when you're ready.

Thanks <3

**Comment by imknight** [comment]
ya sorry for that, been really busy with work recently, will relook into this after I clear my work

**Pull request closed without merging**
