### PR TITLE
Reduce redundant scss

### PR DESCRIPTION
**Pull request by thomasplevy**
Reduces redundant SCSS code. The initial version results in this CSS:

```css
.llms-cols .llms-col {
  width: 100%;
}
@media all and (min-width: 600px) {
  .llms-cols [class*=llms-col-] {
    float: left;
  }
  .llms-cols .llms-col-1 {
    width: 100%;
  }
  .llms-cols .llms-col-2 {
    width: 50%;
  }
  .llms-cols .llms-col-3 {
    width: 33.3333333333%;
  }
  .llms-cols .llms-col-4 {
    width: 25%;
  }
  .llms-cols .llms-col-5 {
    width: 20%;
  }
  .llms-cols .llms-col-6 {
    width: 16.6666666667%;
  }
  .llms-cols .llms-col-7 {
    width: 14.2857142857%;
  }
  .llms-cols .llms-col-8 {
    width: 12.5%;
  }
  .llms-cols .llms-col-9 {
    width: 11.1111111111%;
  }
  .llms-cols .llms-col-10 {
    width: 10%;
  }
  .llms-cols .llms-col-11 {
    width: 9.0909090909%;
  }
  .llms-cols .llms-col-12 {
    width: 8.3333333333%;
  }
}

.llms-flex-cols {
  display: -webkit-box;
  display: -ms-flexbox;
  display: flex;
  -webkit-box-orient: horizontal;
  -webkit-box-direction: normal;
      -ms-flex-flow: row wrap;
          flex-flow: row wrap;
}
.llms-flex-cols [class*=llms-col] {
  -webkit-box-flex: 0;
      -ms-flex: 0 1 auto;
          flex: 0 1 auto;
  width: 100%;
}
@media all and (min-width: 600px) {
  .llms-flex-cols .llms-col-1 {
    width: 100%;
  }
  .llms-flex-cols .llms-col-2 {
    width: 50%;
  }
  .llms-flex-cols .llms-col-3 {
    width: 33.3333333333%;
  }
  .llms-flex-cols .llms-col-4 {
    width: 25%;
  }
  .llms-flex-cols .llms-col-5 {
    width: 20%;
  }
  .llms-flex-cols .llms-col-6 {
    width: 16.6666666667%;
  }
  .llms-flex-cols .llms-col-7 {
    width: 14.2857142857%;
  }
  .llms-flex-cols .llms-col-8 {
    width: 12.5%;
  }
  .llms-flex-cols .llms-col-9 {
    width: 11.1111111111%;
  }
  .llms-flex-cols .llms-col-10 {
    width: 10%;
  }
  .llms-flex-cols .llms-col-11 {
    width: 9.0909090909%;
  }
  .llms-flex-cols .llms-col-12 {
    width: 8.3333333333%;
  }
}
```

The updated version is probably the same number of actual bytes but is more compact:

```css
.llms-cols .llms-col {
  width: 100%;
}
@media all and (min-width: 600px) {
  .llms-cols [class*=llms-col-] {
    float: left;
  }
}

.llms-flex-cols {
  display: -webkit-box;
  display: -ms-flexbox;
  display: flex;
  -webkit-box-orient: horizontal;
  -webkit-box-direction: normal;
      -ms-flex-flow: row wrap;
          flex-flow: row wrap;
}
.llms-flex-cols [class*=llms-col] {
  -webkit-box-flex: 0;
      -ms-flex: 0 1 auto;
          flex: 0 1 auto;
  width: 100%;
}

@media all and (min-width: 600px) {
  .llms-cols .llms-col-1, .llms-flex-cols .llms-col-1 {
    width: 100%;
  }
  .llms-cols .llms-col-2, .llms-flex-cols .llms-col-2 {
    width: 50%;
  }
  .llms-cols .llms-col-3, .llms-flex-cols .llms-col-3 {
    width: 33.3333333333%;
  }
  .llms-cols .llms-col-4, .llms-flex-cols .llms-col-4 {
    width: 25%;
  }
  .llms-cols .llms-col-5, .llms-flex-cols .llms-col-5 {
    width: 20%;
  }
  .llms-cols .llms-col-6, .llms-flex-cols .llms-col-6 {
    width: 16.6666666667%;
  }
  .llms-cols .llms-col-7, .llms-flex-cols .llms-col-7 {
    width: 14.2857142857%;
  }
  .llms-cols .llms-col-8, .llms-flex-cols .llms-col-8 {
    width: 12.5%;
  }
  .llms-cols .llms-col-9, .llms-flex-cols .llms-col-9 {
    width: 11.1111111111%;
  }
  .llms-cols .llms-col-10, .llms-flex-cols .llms-col-10 {
    width: 10%;
  }
  .llms-cols .llms-col-11, .llms-flex-cols .llms-col-11 {
    width: 9.0909090909%;
  }
  .llms-cols .llms-col-12, .llms-flex-cols .llms-col-12 {
    width: 8.3333333333%;
  }
}
```

### CODE REVIEW

**Review by eri-trabiccolo — APPROVED** [review]
Looks good, if only we could use `:is` would have been even smaller. But it's [not supported by IE](https://developer.mozilla.org/en-US/docs/Web/CSS/:is#browser_compatibility).

**Comment by eri-trabiccolo** [comment]
I think it should be against `dev-600` though.

**Comment by thomasplevy** [comment]
`dev-600` is gone as of this morning: https://github.com/gocodebox/lifterlms/pull/2041

We're about to release 6.0 as stable so there's no need to work on a separate branch anymore.

**Comment by eri-trabiccolo** [comment]
> `dev-600` is gone as of this morning: #2041
> 
> We're about to release 6.0 as stable so there's no need to work on a separate branch anymore.

I didn't know it yet

**Pull request merged**
