### PR TITLE
Fix MySQL error when course has no lessons

### PR DESCRIPTION
**Pull request by reedhewitt**
## Description
If a course does not have any lessons yet, the `get_lesson_completions` method would cause a MySQL error.  With this change, the method will return zero if no lessons exist.

## How has this been tested?
Tested on our production site.  The MySQL error no longer occurs and the course report overview shows "0" for lesson completions instead of nothing.

Because this change is so small and the simple, I have not created a test environment and run automated tests.

## Checklist:
- [x] My code has been tested.
- [ ] My code passes all existing automated tests. 
- [ ] My code follows the LifterLMS Coding & Documentation Standards.

### CODE REVIEW

**Comment by reedhewitt** [comment]
Sorry, I did not mean to click "Merge branch 'dev' into trunk"!!!  I'm sure you'll see that because it is pending review.  I hit that button on accident.

**Review by reedhewitt — COMMENTED** [review]
Please disregard this merge request.  I accidentally clicked a button while submitting a pull request.

**Comment by thomasplevy** [comment]
@reedhewitt you want me to close this and you'll reopen? Or you're not going to submit it?

**Comment by reedhewitt** [comment]
@thomasplevy That's probably best if you close the thread.  I'll submit a new pull request and I WON'T click the wrong button this time. : )

**Pull request closed without merging**
