### PR TITLE
Persist the tracking events via ajax when reaching the cookie size li…

### PR DESCRIPTION
**Pull request by eri-trabiccolo**
…mit.

@thomasplevy 

This is a WIP.
I need to add unit tests (functional mostly) and wanted to finish fixing the cs in `class.llms.ajax.handler.php`
I'm not going to finish it today.

Just wanted to have your opinion on the approach - IF AND WHEN you got time -, which I think is basically what we discussed except for the condition that "triggers" the ajax action.

Fixes gocodebox/lifterlms-advanced-videos#23

Bye

### CODE REVIEW

**Comment by thomasplevy** [comment]
@eri-trabiccolo I didn't do a full review but I read through it and it looks like a solid approach to me. I don't see any obvious issues.

I'll do a more thorough review early next week, good work so far

**Comment by eri-trabiccolo** [comment]
Thanks @thomasplevy
Hopefully early next week there will be a final version of this for you to review.

**Comment by thomasplevy** [comment]
@eri-trabiccolo this looks good but I haven't actually tested it yet and I want to run some manual tests before merging. I'm going to do that tomorrow.

**Comment by thomasplevy** [comment]
@eri-trabiccolo I'm seeing an issue here... 

I'm adding fake events to the tracking data by repeatedly running this in the console:

`llms.tracking.addEvent( 'page.focus' )`

Watching the cookie in the sources I can watch the cookie size increase in the Application dev tools tab.

It looks like when the cookie size reaches it max it clears but the AJAX event is not triggered and (I think) the events are just lost.

**Comment by thomasplevy** [comment]
I think I was being dumb...

**Comment by thomasplevy** [comment]
Yep, works perfect... I had some text in the filter box on the XHR tab and therefore didn't see the request going through. This is great <3

**Comment by eri-trabiccolo** [comment]
@thomasplevy ah well that's THE thing that should work... also the cleaning and the ajax call are under the same condition so... I'm going to check in 2 minutes.

**Pull request merged**
