### PR TITLE
Release: Version 4.12.0

### LINKED ISSUE #1258: Pagination breaks for [lifterlms_courses] shortcode when embedded on homepage
I know embedding things on the homepage can cause issues. This is likely one of those times :-)

### Reproduction Steps

- Embed a `[lifterlms_courses]` shortcode on the homepage
- Set it to display a limited # of courses so they will be paginated
- Go to homepage, click on the pagination links and the courses won't update

### Expected Behavior

The courses update based on the page # clicked

### Actual Behavior

The courses remain on page one.

This issue has be recreated:
+ [x] Locally
+ [ ] On a staging site
+ [x] On a production website
+ [ ] With only LifterLMS and a default theme

You can experience yourself on [the Gravity.guide](https://gravity.guide/) homepage.

### LINKED ISSUE #1487: Calling `wp_nav_menu()` before `init` (10) hook raises a fatal
### Reproduction Steps
This is a simplified way to reproduce it. See the section Related User Information for the real case bug reporting.

+ Make sure you have at least one menu created
+ Execute this code:
```php	add_action( 'init', 'wp_nav_menu', 0 );```

### Expected Behavior

+ a nav menu printed at init|0.

### Actual Behavior

+ Fatal error

I just simplified

### Error Messages / Logs

```
PHP Fatal error:  Uncaught Error: Call to undefined function is_lifterlms() in /shared/httpd/mywp/wordpress.git/wp-content/plugins/lifterlms/includes/class.llms.nav.menus.php:224
```

### System and Environment Information

LifterLMS 4.11.0
WordPress 5.6

## This issue has been recreated:
+ [x] Locally
+ [x] On a staging site
+ [x] On a production website
+ [x] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

n/a

### Related User Information
https://wordpress.org/support/topic/bug-report-conflict-with-edd-email-templates-and-lifterlms-template-functions/

The user provides in depth information on how this issue occurs on their website and how they fixed it for their specific case.

This very issue could be fixed by checking whether the function exists before using it, yet the issue is more general and maybe we need to think to a more generic approach.

### PR DESCRIPTION
**Pull request by thomasplevy**
+ Fixes #1258 via #1489
+ Fixes #1487 via #1488
+ PR #1481 
+ PR #1485 (Per #1484)
+ PR #1486 
+ PR #1492
+ PR #1493

### CODE REVIEW

**Comment by thomasplevy** [comment]
@eri-trabiccolo I can't figure out why this test is failing in all these various PRs since merging it into dev (but only intermittently)

I can't reproduce locally. Can you have a look at the method and see if you can see any reasoning for what's happening?

https://github.com/gocodebox/lifterlms/blob/3a00b616c9abfdcdd8bbad3f59b7d93b4d0a2c2e/tests/phpunit/unit-tests/processors/class-llms-test-processor-course-data.php#L333

**Comment by eri-trabiccolo** [comment]
@thomasplevy when it's that random my first guess is always something wrong with the query "order by".
By default the first order param of a student query is the `date` (desc) ..., while we expect the page sorted by `id`...
Pushing a PR and we'll see.

**Comment by eri-trabiccolo** [comment]
fixed in #1494

**Comment by thomasplevy** [comment]
Yes I'm almost positive this is it. Good catch thank you <3

**Comment by thomasplevy** [comment]
[lifterlms-4.12.0.zip](https://github.com/gocodebox/lifterlms/files/5839165/lifterlms-4.12.0.zip)

I can't get this shipped tonight, waiting on Travis and have to run. I'll rebuild with tomorrows date and release in the morning

**Pull request merged**
