### PR TITLE
add docblock

### LINKED ISSUE #1982: Document the `llms_new_{$this->model_post_type}` filter
Maybe we can take this occasion to add a the documentation to this filter?

_Originally posted by @eri-trabiccolo in https://github.com/gocodebox/lifterlms/pull/1946#discussion_r802432246_

Document the `llms_new_{$this->model_post_type}` filter in `LLMS_Post_Model::create()`.

### PR DESCRIPTION
**Pull request by thomasplevy**
## Description
Fixes #1982

## How has this been tested?
Unit tests

## Types of changes
Docs

## Checklist:
- [x] My code has been tested.
- [x] My code passes all existing automated tests. 
- [x] My code follows the LifterLMS Coding & Documentation Standards.

### CODE REVIEW

**Comment by thomasplevy** [comment]
@eri-trabiccolo if you pay attention you'll see this is very clearly NOT assigned to, nor have I requested a review from you. So back off. Unless you're going to upload a picture of a rock I don't want to see you anywhere near this PR.

**Comment by eri-trabiccolo** [comment]
I tried, didn't work, sorry.

**Review by nrherron92 — APPROVED** [review]
This 🪨 s

**Pull request merged**
