### PR TITLE
Removed empty html markup.

### PR DESCRIPTION
**Pull request by dcmayankavi**
Issue: https://goo.gl/2T7ubm

### CODE REVIEW

**Comment by thomasplevy** [comment]
@dcmayankavi i realize empty markup is pending as #417 but the whitespace created by the empty featured element is allowing access plans to align visually when one is featured and the others are not. I'm sure there's a better solution than what's currently in core but moving the if statement as this PR does will create a new bug!

test_some_engagements_-_lifterlms_demo_site

**Comment by thomasplevy** [comment]
now that i'm thinking about this the trial empty markup may be serving the exact same purpose too... i need to do some more testing on it to confirm

**Comment by dcmayankavi** [comment]
@thomasplevy, Instead of adding empty markup you can add a class for `non-featured` element which will add top margin, or you can add the top margin as per other's height using JS. I'm not sure but I think instead of using empty markup you can use other solutions as for that.

**Comment by thomasplevy** [comment]
those sound like good solutions, want to update the PR or should I close this?

**Comment by thomasplevy** [comment]
Closing and will track on #417

**Pull request closed without merging**
