### PR TITLE
Correct post_type of "Mine"

### LINKED ISSUE #1365: [wp-admin] List courses: Mine always shows zero, click it go to list of Posts instead of Courses
### Reproduction Steps

+ Include clear and detailed step by step instructions on how the issue can be reliably reproduced

1. Setup just another WordPress.
2. Install LifterLMS plugin.
3. Create a sample course.
4. In Admin Dashboard, go to Courses > Courses to view list of courses.

+ Include screenshots where applicable
image

### Expected Behavior

+ Include a concise description of what you expected to happen (but didn't)

"Mine" should be 1.
Click to "Mine" should stay til in Courses > Courses.

### Actual Behavior

+ Include a concise description of what actually happens (but isn't supposed to)

"Mine" is 0.
Click "Mine" jump to Posts > All Posts.

### System and Environment Information

This issue has be recreated:
+ [x] Locally
+ [x] On a staging site
+ [x] On a production website
+ [x] With only LifterLMS and a default theme

### PR DESCRIPTION
**Pull request by nhandl3**
## Description

Fixes #1365 

## How has this been tested?

Manually, with existing unit tests.

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code has been tested.
- [x] My code passes all existing automated tests. 
- [x] My code follows the LifterLMS Coding & Documentation Standards.

### CODE REVIEW

**Review by eri-trabiccolo — CHANGES_REQUESTED** [review]
Hi @nhandl3 thanks for your contribution!

We would like to keep track of the changes we did in 3.35.0 in the `get_views()` changelog, so rather  then modifying this:
`@since 3.35.0 Verify nonces and sanitize `$_POST` data.`
would be better to add a new `@since` with the changes made in this very PR.
You can use the `[version]` placeholder instead of trying to guess what version this change will be released with, as described in our documentation standards:
https://github.com/gocodebox/lifterlms/blob/trunk/docs/documentation-standards.md#using-placeholders

Still using the placeholder above you might want to change this line:
https://github.com/gocodebox/lifterlms/blob/a462166382abb35f573753dcf86f64922af0776c/includes/admin/post-types/post-tables/class.llms.admin.post.table.instructors.php#L8

according to:
https://github.com/gocodebox/lifterlms/blob/trunk/docs/documentation-standards.md#file-headers

Please let me know if I've been not clear. 

Thanks again! <3

**Comment by nhandl3** [comment]
Thanks to point out that part @eri-trabiccolo !
I was indeed confused whether or not documenting version.
I amended the work as your review to avoid bloating commits :)

**Review by eri-trabiccolo — APPROVED** [review]
fine for me @nhandl3 thanks!

**Comment by thomasplevy** [comment]
@eri-trabiccolo I haven't physically run this but can you confirm that you've checked it out and run it (and that it resolves #1365)

With that confirmation I'll merge it and schedule for release this week.

And thank you @nhandl3 !

**Comment by eri-trabiccolo** [comment]
@thomasplevy I confirm yes. <3

**Pull request merged**
