### PR TITLE
Release Version 5.3.0

### LINKED ISSUE #1742: Fatal Error on Quiz Attempts with Deleted Questions
### Reproduction Steps

+ HS-172678
+ Create a quiz
+ Have student take the quiz
+ Delete a quiz question after user took quiz
+ grade user's attempt and click submit review

### Expected Behavior

+ It saves.

### Actual Behavior

+ A fatal terror 

### Error Messages / Logs

+ Include any relevant error messages or log files
```
Fatal error: Uncaught Error: Call to a member function get_auto_grade_type() on null in /srv/users/manager/apps/natalie-customfields-test/public/wp-content/plugins/lifterlms/includes/models/model.llms.quiz.attempt.question.php:267 Stack trace: #0 /srv/users/manager/apps/natalie-customfields-test/public/wp-content/plugins/lifterlms/includes/models/model.llms.quiz.attempt.php(664): LLMS_Quiz_Attempt_Question->get_status() #1 /srv/users/manager/apps/natalie-customfields-test/public/wp-content/plugins/lifterlms/includes/models/model.llms.quiz.attempt.php(161): LLMS_Quiz_Attempt->is_auto_gradeable() #2 /srv/users/manager/apps/natalie-customfields-test/public/wp-content/plugins/lifterlms/includes/controllers/class.llms.controller.admin.quiz.attempts.php(115): LLMS_Quiz_Attempt->calculate_grade() #3 /srv/users/manager/apps/natalie-customfields-test/public/wp-content/plugins/lifterlms/includes/controllers/class.llms.controller.admin.quiz.attempts.php(69): LLMS_Controller_Admin_Quiz_Attempts->save_grade(Object(LLMS_Quiz_Attempt)) in /srv/users/manager/apps/natalie-customfields-test/public/wp-content/plugins/lifterlms/includes/models/model.llms.quiz.attempt.question.php on line 267


```

### System and Environment Information

<details>
<summary>System Report</summary>

```
Wordpress
-------------------------------------------

Home Url: https://natalie-customfields-test.myliftersite.com
Site Url: https://natalie-customfields-test.myliftersite.com
Login Url: https://natalie-customfields-test.myliftersite.com/wp-login.php
Version: 5.8
Debug Mode: No
Debug Log: No
Debug Display: Yes
Locale: en_US
Multisite: No
Page For Posts: Not Set
Page On Front: Not Set
Permalink Structure: /%postname%/
Show On Front: posts
Wp Cron: Yes


Settings
-------------------------------------------

Version: 5.2.0
Db Version: 5.2.0
Course Catalog: Course Catalog (#14) [https://natalie-customfields-test.myliftersite.com/courses/]
Membership Catalog: Membership Catalog (#15) [https://natalie-customfields-test.myliftersite.com/memberships/]
Student Dashboard: Dashboard (#17) [https://natalie-customfields-test.myliftersite.com/dashboard/]
Checkout Page: Purchase (#16) [https://natalie-customfields-test.myliftersite.com/purchase/]
Course Catalog Per Page: 9
Course Catalog Sorting: menu_order
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order
Site Membership: Not Set
Courses Endpoint: my-courses
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: redeem-voucher
Autogenerate Username: yes
Password Strength Meter: yes
Minimum Password Strength: strong
Terms Required: no
Terms Page: Not Set
Checkout Names: required
Checkout Address: required
Checkout Phone: optional
Checkout Email Confirmation: yes
Open Registration: yes
Registration Names: required
Registration Address: optional
Registration Phone: hidden
Registration Voucher: optional
Registration Email Confirmation: no
Account Names: required
Account Address: required
Account Phone: optional
Account Email Confirmation: yes
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: no
Country: US
Currency: USD
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: yes
Email From Address: team+sandbox@lifterlms.com
Email From Name: A LifterLMS Sandbox
Email Footer Text: 
Email Header Image: 
Cert Bg Width: 800
Cert Bg Height: 616
Cert Legacy Compat: no


Constants
-------------------------------------------

LLMS_REMOVE_ALL_DATA: undefined
LLMS_REST_DISABLE: undefined
LLMS_SITE_FEATURE_RECURRING_PAYMENTS: undefined
LLMS_SITE_IS_CLONE: undefined


Gateways
-------------------------------------------

Stripe: Enabled
Stripe Test Mode: Enabled
Stripe Logging: no
Stripe Order: 1
Manual: Disabled
Manual Logging: 
Manual Order: 1


Server
-------------------------------------------

Mysql Version: 5.7.35
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 5000
Php Max Upload Size: 512 MB
Php Memory Limit: 256M
Php Post Max Size: 1024M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 30
Php Version: 7.3.29
Software: Apache/2.4.48 (Unix) OpenSSL/1.1.1
Wp Memory Limit: 256M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36


Theme
-------------------------------------------

Name: Astra
Version: 3.6.4
Themeuri: https://wpastra.com/
Authoruri: https://wpastra.com/about/
Template: 
Child Theme: No
Llms Support: Yes


Plugins
-------------------------------------------

LifterLMS: 5.2.0
LifterLMS Advanced Quizzes: 1.1.1
LifterLMS Custom Fields: 2.0.1
LifterLMS Stripe Payment Gateway: 5.3.2
Loco Translate: 2.5.3
User Switching: 1.5.7


Integrations
-------------------------------------------

BbPress: No
BuddyPress: No


Template Overrides
-------------------------------------------




```

</details>

This issue has be recreated:
+ [X] Locally
+ [X] On a staging site
+ [X] On a production website
+ [X] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)

### LINKED ISSUE #1746: Implement usage of traits
LifterLMS is long overdue to use PHP traits. I often wish to add a trait for something but don't want to include the required "prework" in the related bugfix / feature PR.

+ Trait classes should follow the naming convention `LLMS_Trait_{$trait}`, eg: `LLMS_Trait_Singleton`.
+ Trait files should follow the naming convention `llms-trait-{$trait}.php`: eg: `llms-trait-singleton.php`
+ Trait classes should be stored in their own directory at `includes/traits`
+ Traits should be autoloaded via the `LLMS_Loader::autoload()` method

An initial singleton trait can be included and singleton classes in the core can remove their singleton methods and properties and be replaced with the new trait.

+ A singleton trait exists in the lifterlms-rest library: https://github.com/gocodebox/lifterlms-rest/blob/trunk/includes/traits/class-llms-rest-trait-singleton.php. I believe this can be lifted into the core (and ultimately replaced in the rest lib as the core's singleton could then be used).

+ the sales page redirect methods "shared" (duplicated) across courses and memberships (see #1743) can be converted into a "sales page" type trait containing these methods that can then be mixed into the course and membership models.

+ Audio and video embed code is similarly copied between courses and memberships

This would be a good start. There's lots of other potential areas where we could replace duplicated code with traits too but these jump out at me immediately.

+ Existing tests should continue to pass if traits are implemented properly.
+ When creating new traits I feel the best practice would be to instantiate a mock (anonymous?) class that uses the trait and write tests against the mock. However, for the purposes of ensuring the traits "integrate" properly having redundant tests for some traits *might* make sense. The sales page / redirect trait might benefit from having course/membership model tests AND having tests against an anonymous class that uses the trait out of the "intended" context

### LINKED ISSUE #1753: LocoTranslate File overload
### Reproduction Steps

+ HS-173472
+ With LifterLMS and LocoTranslate go into _Loco Translate->Plugins->LifterLMS Overview_
image

### Expected Behavior

+ Everything works as normal, the notice is just concerning

### Actual Behavior

+ The notice shouldn't be there since these are already included in the core and aren't extra files needed to make translations?

### Error Messages / Logs

+ Include any relevant error messages or log files
```
<!-- Paste error logs / backtraces below this line -->

```

### System and Environment Information

<details>
<summary>System Report</summary>

```
Wordpress
-------------------------------------------

Home Url: https://natalie-customfields-test.myliftersite.com
Site Url: https://natalie-customfields-test.myliftersite.com
Login Url: https://natalie-customfields-test.myliftersite.com/wp-login.php
Version: 5.8
Debug Mode: No
Debug Log: No
Debug Display: Yes
Locale: en_US
Multisite: No
Page For Posts: Not Set
Page On Front: Not Set
Permalink Structure: /%postname%/
Show On Front: posts
Wp Cron: Yes


Settings
-------------------------------------------

Version: 5.2.0
Db Version: 5.2.0
Course Catalog: Course Catalog (#14) [https://natalie-customfields-test.myliftersite.com/courses/]
Membership Catalog: Membership Catalog (#15) [https://natalie-customfields-test.myliftersite.com/memberships/]
Student Dashboard: Dashboard (#17) [https://natalie-customfields-test.myliftersite.com/dashboard/]
Checkout Page: Purchase (#16) [https://natalie-customfields-test.myliftersite.com/purchase/]
Course Catalog Per Page: 9
Course Catalog Sorting: menu_order
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order
Site Membership: Not Set
Courses Endpoint: my-courses
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: redeem-voucher
Autogenerate Username: yes
Password Strength Meter: yes
Minimum Password Strength: strong
Terms Required: no
Terms Page: Not Set
Checkout Names: required
Checkout Address: required
Checkout Phone: optional
Checkout Email Confirmation: yes
Open Registration: yes
Registration Names: required
Registration Address: optional
Registration Phone: hidden
Registration Voucher: optional
Registration Email Confirmation: no
Account Names: required
Account Address: required
Account Phone: optional
Account Email Confirmation: yes
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: no
Country: US
Currency: USD
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: yes
Email From Address: team+sandbox@lifterlms.com
Email From Name: A LifterLMS Sandbox
Email Footer Text: 
Email Header Image: 
Cert Bg Width: 800
Cert Bg Height: 616
Cert Legacy Compat: no


Constants
-------------------------------------------

LLMS_REMOVE_ALL_DATA: undefined
LLMS_REST_DISABLE: undefined
LLMS_SITE_FEATURE_RECURRING_PAYMENTS: undefined
LLMS_SITE_IS_CLONE: undefined


Gateways
-------------------------------------------

Stripe: Enabled
Stripe Test Mode: Enabled
Stripe Logging: no
Stripe Order: 1
Manual: Disabled
Manual Logging: 
Manual Order: 1


Server
-------------------------------------------

Mysql Version: 5.7.35
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 5000
Php Max Upload Size: 512 MB
Php Memory Limit: 256M
Php Post Max Size: 1024M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 30
Php Version: 7.3.29
Software: Apache/2.4.48 (Unix) OpenSSL/1.1.1
Wp Memory Limit: 256M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36


Theme
-------------------------------------------

Name: OceanWP
Version: 3.0.3
Themeuri: https://oceanwp.org/
Authoruri: https://oceanwp.org/about-me/
Template: 
Child Theme: No
Llms Support: No


Plugins
-------------------------------------------

LifterLMS: 5.2.0
LifterLMS Advanced Quizzes: 1.1.1
LifterLMS Custom Fields: 2.0.1
LifterLMS Stripe Payment Gateway: 5.3.2
Loco Translate: 2.5.3
Redirection: 5.1.3
User Switching: 1.5.7
WP Mail Logging: 1.9.8


Integrations
-------------------------------------------

BbPress: No
BuddyPress: No


Template Overrides
-------------------------------------------




```

</details>

This issue has be recreated:
+ [X] Locally
+ [X] On a staging site
+ [X] On a production website
+ [X] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

+ Browser name and version
+ Operating System name and version
+ Device name and version (if applicable)

### PR DESCRIPTION
**Pull request by thomasplevy**
+ Fixes gocodebox/private-issues#37 via #1744 & #1760
+ Fixes #1742 via #1749
+ Fixes #1753 via #1754 
+ Closes #1746 via #1758 & #1756
+ #1761
+ gocodebox/lifterlms-launchpad#33 via #1763

### CODE REVIEW

**Comment by thomasplevy** [comment]
@eri-trabiccolo & @pondermatic This is a pretty big release that affects a lot of files. I've finished up my pre-release testing and I think it's good but can you each give me another look over this and give me a yay/nay to proceed with shipping. I'd like to ship tomorrow sometime before noonish my time. Thanks

Please: hold your code review suggestions unless you see anything earth shattering. I've already built the release and I don't want to rebuild and retest for documentation changes. If you do see something say something. Docs: update in a new PR to ship later. If you find an issue that requires us to actually fix something we'll of course rebuild. Leave a note and we'll discuss tomorrow. I'm not rebuilding for docs or typos. Thanks <3

[lifterlms-5.3.0.zip](https://github.com/gocodebox/lifterlms/files/7079958/lifterlms-5.3.0.zip)

**Review by eri-trabiccolo — APPROVED** [review]
I tested it on a fresh install too.
It looks good to me.

**Comment by pondermatic** [comment]
I'm getting a strange behavior with the unit tests that I've never seen before. The first 277 tests pass, then the following is printed and testing stops with exit code 0.
```
"Order ID","Expected Payments","Total Payments","Successful Payments","Refunded Payments","Edit Link"
258,2,0,0,0,http://example.org/wp-admin/post.php?post=258&action=edit
259,2,0,0,0,http://example.org/wp-admin/post.php?post=259&action=edit
260,2,0,0,0,http://example.org/wp-admin/post.php?post=260&action=edit
```
That first line is from [LLMS_Test_Admin_Tool_Limited_Billing_Order_Locator::test_handle()](https://github.com/gocodebox/lifterlms/blob/dev/tests/phpunit/unit-tests/admin/tools/class-llms-test-admin-tool-limited-billing-order-locator.php#L223)

Hopefully, it's something that's changed on my development system, but I am looking into it.

**Comment by thomasplevy** [comment]
@pondermatic `rm -rf vendor && composer install` -- you're likely missing the latest version of lifterlms-tests which includes: https://github.com/gocodebox/lifterlms-tests/blob/472c5a286e9f65e2be0c1d6b7edd8d5340d052ed/framework/functions-llms-tests.php#L164-L176

**Comment by pondermatic** [comment]
Thank you @thomasplevy. Updating lifterlms-test did help. The output I was seeing was the CSV file from `LLMS_Admin_Tool_Limited_Billing_Order_Locator->get_csv_file()`.

Unfortunately, LLMS_Test_Admin_Tool_Limited_Billing_Order_Locator::test_handle() is failing. Only the header row is expected but I'm seeing all 4 rows.

**Comment by pondermatic** [comment]
The CSV file has Unix line endings. The test is expecting PHP_EOL native line endings.

**Comment by thomasplevy** [comment]
@pondermatic we can fix this later... the tests are passing for me locally (and on travis)

I'm more concerned with ensuring the actual distribution installs and runs... line ending type doesn't really matter one bit functionally, but we can of course change the test so it passes on your machine too.

**Comment by pondermatic** [comment]
@thomasplevy, I think it's OK that `fputcsv()` uses `\n` line endings, even when running on Windows. Changing the unit test to use `\n` allows it to pass.

I'm testing the full suite now.

**Comment by thomasplevy** [comment]
Looks like windows expects `\r\n` and the advice I'm reading is to simply *not use* PHP_EOL in most circumstances... It seems silly to me that PHP itself isn't using `PHP_EOL` to add endlines in the CSV... I'm going to update the test. At the moment I'm more concerned with making sure there's no issues in the release itself. This is a testing suite issue cropping up in a Windows environment (as far as I can tell)

**Review by pondermatic — APPROVED** [review]

**Comment by pondermatic** [comment]
I'm surprised that `fputcsv()` doesn't use PHP_EOL and that the documentation does not mention that it always uses `\n`, even on windows. Most "good" software can handle any line ending standard.

**Pull request merged**
