### PR TITLE
Upcoming payment reminder

### PR DESCRIPTION
**Pull request by niluzok**
## Description
I added a notification about the upcoming recurrent payment. Notification is scheduled on 1 day before payment due date.

## How has this been tested?
I ve done only manual testing. I created several orders with recurrent payments, than looked for scheduled actions and their dates: actual payment and notification the day before. Than i ran this scheduled actions by hand and watched as they reappeared. Than i tested order due date change and order cancelation.

## Types of changes
- New notification controller + view
- Added code for scheduling and unscheduling notification invocation in order model next to code for scheduling and unscheduling or recurrent payments

## Checklist:
- [ ] My code has been tested.
- [ ] My code passes all existing automated tests. 
- [x] My code follows the LifterLMS Coding & Documentation Standards.

### CODE REVIEW

**Comment by thomasplevy** [comment]
@niluzok thanks for your contribution!

Before we start a human review would you please fix the coding standards issues identified by the travis build(s)?

You can fix most of these by running `composer run fix-cs` and the last remaining check that cannot be fixed automatically is quite simple to fix.

Have a look at these docs if you're not sure where to start: https://github.com/gocodebox/lifterlms/blob/trunk/docs/installing.md

Thanks!

**Comment by thomasplevy** [comment]
@niluzok bump!

**Comment by niluzok** [comment]
Ok, i fixed some errors. One error stays: "Missing @ since tag in file comment"

**Comment by niluzok** [comment]
@thomasplevy

**Comment by thomasplevy** [comment]
@niluzok we'll be adding tests when some capacity allows and integrating this into a future release. If you'd like to write some tests that'll speed the process up otherwise we appreciate your patience!

And thanks again for your PR

**Comment by niluzok** [comment]
@thomasplevy do you have a manual for How to write and run tests for LLMS?

**Comment by thomasplevy** [comment]
@niluzok of course: 

phpunit: https://github.com/gocodebox/lifterlms/tree/trunk/tests/phpunit
e2e (Jest & Puppeteer): https://github.com/gocodebox/lifterlms/tree/trunk/tests/e2e

**Comment by thomasplevy** [comment]
Closing in favor of #1545

**Pull request closed without merging**
