### PR TITLE
Fix various issues when adding existing lessons/quizzes/assignments

### PR DESCRIPTION
**Pull request by eri-trabiccolo**
## Description

Fixes https://github.com/gocodebox/private-issues/issues/41

## How has this been tested?
manually

## Types of changes
Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code has been tested.
- [x] My code passes all existing automated tests. 
- [x] My code follows the LifterLMS Coding & Documentation Standards.

### CODE REVIEW

**Comment by thomasplevy** [comment]
I know that I put forth the precedent of having assignments code in the core codebase but it's kind of a terrible precedent. I don't have a good rule for when code should or should not be in the assignments add-on (obviously) but this adds more logic for handling assignments into the core and further complicates the preexisting issue.

Did you consider any of this or try to add this code to the assignments addon using JS hooks? This might not be that hard to do.

Thoughts?

**Comment by eri-trabiccolo** [comment]
> I know that I put forth the precedent of having assignments code in the core codebase but it's kind of a terrible precedent. I don't have a good rule for when code should or should not be in the assignments add-on (obviously) but this adds more logic for handling assignments into the core and further complicates the preexisting issue.
> 
> Did you consider any of this or try to add this code to the assignments addon using JS hooks? This might not be that hard to do.
> 
> Thoughts?

I could do that, but the whole Assignment view is in core, so ideally I had to do a small change in the view in core and a small (though bigger than the one in the view) change in the assignment add-on. I can.
Fine for you to keep the Assignment view's changes in core?

**Comment by eri-trabiccolo** [comment]
@thomasplevy see https://github.com/gocodebox/lifterlms/pull/1808/commits/dde8ad5a9c33c1173e3796e783487702c74f16ba
and
https://github.com/gocodebox/lifterlms-assignments/pull/68
does this make more sense?
It seems a little bit clumsy to me tbh having the assignments view in core...

**Comment by eri-trabiccolo** [comment]
So we decided to revert the moving assignment cloning logic in the assignment add-on, as most of the involved entities are already in core.

**Pull request merged**
