### PR TITLE
Corrected Italian provinces, and added missing ones.

### LINKED ISSUE #2256: Italian province of Trento written wrong, and lack of two Italian provinces (Mantova and Verona)
### Reproduction Steps

in the selection of the province of the registration form or profile modification

### Expected Behavior

There must be the province of Trento, Mantova and Verona

### Actual Behavior

The "Trentino" province does not exist, the "Trento" province does exist, the provinces of Mantua and Verona are missing

### Error Messages / Logs

+ Include any relevant error messages or log files
```
<!-- Paste error logs / backtraces below this line -->

```

### System and Environment Information

<details>
<summary>System Report</summary>

```
Wordpress
-------------------------------------------

Home Url: https://academy.bluenext.it
Site Url: https://academy.bluenext.it
Login Url: https://academy.bluenext.it/wp-login.php
Version: 6.0.2
Debug Mode: No
Debug Log: No
Debug Display: Yes
Locale: it_IT
Multisite: No
Page For Posts: Not Set
Page On Front: Home Page (#1372) [https://academy.bluenext.it/]
Permalink Structure: /%postname%/
Show On Front: page
Wp Cron: Yes


Settings
-------------------------------------------

Version: 6.10.1
Db Version: 6.10.1
Course Catalog: Catalogo Corsi (#16) [https://academy.bluenext.it/?page_id=16]
Membership Catalog: Catalogo Membership (#17) [https://academy.bluenext.it/?page_id=17]
Student Dashboard: Area Riservata (#1317) [https://academy.bluenext.it/area-riservata/]
Checkout Page: Acquisti (#18) [https://academy.bluenext.it/purchase/]
Course Catalog Per Page: 9
Course Catalog Sorting: menu_order
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order
Site Membership: Not Set
Courses Endpoint: my-courses
Edit Endpoint: modifica-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: redeem-voucher
Autogenerate Username: no
Password Strength Meter: no
Minimum Password Strength: 
Terms Required: no
Terms Page: Not Set
Checkout Names: 
Checkout Address: 
Checkout Phone: 
Checkout Email Confirmation: no
Open Registration: no
Registration Names: 
Registration Address: 
Registration Phone: 
Registration Voucher: 
Registration Email Confirmation: no
Account Names: 
Account Address: 
Account Phone: 
Account Email Confirmation: no
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: no
Country: IT
Currency: EUR
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: yes
Email From Address: formazione@bluenext.it
Email From Name: Bluenext Academy
Email Footer Text: 
Email Header Image: 
Cert Bg Width: 800
Cert Bg Height: 616
Cert Legacy Compat: no


Constants
-------------------------------------------

LLMS_REMOVE_ALL_DATA: undefined
LLMS_REST_DISABLE: undefined
LLMS_SITE_FEATURE_RECURRING_PAYMENTS: undefined
LLMS_SITE_IS_CLONE: undefined


Gateways
-------------------------------------------

Stripe: Enabled
Stripe Test Mode: Disabled
Stripe Logging: no
Stripe Order: 1
Manuale: Disabled
Manuale Logging: no
Manuale Order: 1


Server
-------------------------------------------

Mysql Version: 5.7.39
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 10000
Php Max Upload Size: 50 MB
Php Memory Limit: 512M
Php Post Max Size: 100M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 3600
Php Version: 7.4.28
Software: Apache
Wp Memory Limit: 40M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36


Theme
-------------------------------------------

Name: LifterLMS LaunchPad Child
Version: 1.1.0
Themeuri: https://lifterlms.com/product/launchpad/
Authoruri: https://lifterlms.com
Template: lifterlms-launchpad
Child Theme: Yes
Llms Support: No


Plugins
-------------------------------------------

Cookiebot | GDPR/CCPA Compliant Cookie Consent and Control: 4.1.1
Elementor: 3.7.4
Elementor Pro: 3.7.5
Events Widgets For Elementor And The Events Calendar: 1.5.2
FluentCRM - Marketing Automation For WordPress: 2.5.95
Genesis Blocks: 1.5.1
LifterLMS: 6.10.1
LifterLMS Blocks: 2.4.3
LifterLMS Custom Fields: 2.0.2
LifterLMS Labs: 1.6.0
LifterLMS Stripe Payment Gateway: 5.4.0
Login as User: 1.4.4
PublishPress Capabilities: 2.5.0
Simple Custom CSS and JS: 3.40
The Events Calendar: 6.0.0.1
Toolset Blocks: 1.6.3
Toolset Module Manager: 1.8.8
Toolset Types: 3.4.16
WP All Import: 3.6.8
WP Engine Smart Plugin Manager: 5.12.8
WPForms: 1.7.6
WPForms Stripe: 2.6.1
WPForms User Registration: 2.1.0
WP Mail Logging: 1.10.4
WP Mail SMTP: 3.5.2
Yoast Duplicate Post: 4.5
Yoast SEO: 19.6.1


Integrations
-------------------------------------------

BbPress: No
BuddyPress: No


Template Overrides
-------------------------------------------

content-certificate.php (ver: 6.0.0): /nas/content/live/bluenext/wp-content/themes/lifterlms-launchpad-child-trunk//lifterlms/ (ver: 4.21.0)
checkout/form-checkout.php (ver: 5.0.0): /nas/content/live/bluenext/wp-content/themes/lifterlms-launchpad-child-trunk//lifterlms/ (ver: 5.0.0)
emails/header.php (ver: 3.16.15): /nas/content/live/bluenext/wp-content/themes/lifterlms-launchpad-child-trunk//lifterlms/ (ver: 3.16.15)



```

</details>

This issue has be recreated:
+ [X] Locally
+ [X] On a staging site
+ [X] On a production website
+ [ ] With only LifterLMS and a default theme

### PR DESCRIPTION
**Pull request by nrherron92**
Can I get some feed back on what our resident Italian @eri-trabiccolo has to say about these alleged places in Italy?

## Description
Added and corrected missing and incorrect Italian Provinces 

Fixes #2256 

## How has this been tested?
Manually in checkout, registration, and edit account forms

## Types of changes
Bug fix

## Checklist:
- [x] My code has been tested.
- [ ] My code passes all existing automated tests. 
- [ ] My code follows the LifterLMS Coding & Documentation Standards.

### CODE REVIEW

**Comment by eri-trabiccolo** [comment]
:D @nrherron92 
Yeah I will, looks pretty good on a first sight? You got them from WooCommerce, right?
I need to understand where some removed stuff ended to go, like Olbia-Tempio people where should be moved?
Gonna check and let you know, then based on this we need to probably do write some migration code similar to this:
https://github.com/gocodebox/lifterlms/pull/2246/files#diff-8fdf445be82a93fd258d85ee35108271cac170a0f2f723f0d5a3251bb762ec09
(and related unit tests)

**Comment by nrherron92** [comment]
Yeah, I merged it from Woo's list. Thank you <3

**Comment by eri-trabiccolo** [comment]
The Sardinia's provinces are quite a complicated issue. Provinces have changed but the changes proposed in this PR are not the up to date. That's the thing.
In our code we have the following provinces for the Sardinia region:
1) Cagliari
2) Carbonia-Iglesias
3) Medio Campidano
4) Nuoro
5) Ogliastra
6) Olbia-Tempio
7) Oristano
8) Sassari

these have been changed just a bit, mostly in how they're called. diff below:
1) same name (Cagliari), same towns/cities except Seulo (now part of Nuoro - 4)) and Seui (previously part of Ogliastra -5)) and Genoni (previously part of Oristano 7))
2) renamed to **Sulcis Iglesiente**
3) same
4) same
5) Same name, same cities except Seui (now part of Cagliari 1))
6) renamed to **North-East Sardinia**, same cities
7) Same name, same cities except Genoni (now part of Cagliari 1))
8) same name, same cities
(reference https://temi.camera.it/leg18/post/la-riforma-delle-province-e-citt-metropolitane-in-sardegna-1.html)

As far as I understood (I'm struggling to find a consistent document) there were no changes on their abbreviations, so aside from a couple of cities who have been "moved" in a different province I think we're fine, we should just update some names. Yeah we could go with DB update (query all the users of the impacted cities and migrate the provinces) but I don't think it's worthwhile.

For all the rest that regards to the changes in this PR, I think we're just translating some city names from the English name (e.g. Mantua), to the original Italian name (e.g. Mantova). I don't think we have to do that to be honest. We always imply that the base language is English, and Roma it's Rome in English, so I would keep that.
The only valid exceptions here are:
1) Trentino -> Trento: this is a needed change as Trentino is the name of the region where Trento come from. Trento is the name of the city and province
2) South Tyrol -> Bolzano: Bolzano is also, rarely, called SudTirol, but Bolzano is better
3) Benevento Province -> Benevento (for brevity and consistency)
4) Massa and Carrara -> Massa-Carrara (that's the true name)
5) Pesaro and Urbino Province -> Pesaro and Urbino (for brevity and consistency - note the "and" in english instead of the "e" in italian)

@nrherron92 can you the update this PR with the information in this comment?
Let me know if there's something unclear <3

**Comment by nrherron92** [comment]
@eri-trabiccolo thank you for all the research! I'll get these updated tomorrow and have you review again <3

**Comment by eri-trabiccolo** [comment]
@actuallyakash 
when you got time can you take over this?

**Comment by actuallyakash** [comment]
hey @eri-trabiccolo 

Just pushed the files with the changes, thank you for the extensive research feedback. Let me know if the update file version (7.2.0) is correct. IDK if any command is used to create it automatically or if it's created manually.

I've assumed 7.2.0 as that'll be the next milestone.

**Comment by eri-trabiccolo** [comment]
@actuallyakash 
instead on pushing to @nrherron92 branch (on her repository) would you mind creating a PR from yours?
Gonna close this <3

**Pull request closed without merging**
