### PR TITLE
Early review for Akismet Feature Addition

### PR DESCRIPTION
**Pull request by thomasplevy**
For code review, per #1044 

Low priority.

### CODE REVIEW

**Comment by eri-trabiccolo** [comment]
We should consider leveraging the wp api to add "suggestions" on updating the privacy policy page, when this feature is enabled.

**Comment by eri-trabiccolo** [comment]
why did you close this?
I'm sorry for being late but I didn't think I was thaaat late...

**Comment by thomasplevy** [comment]
@eri-trabiccolo changing priorities. It didn't work for the test user (at all) to block any amount of spam

**Comment by eri-trabiccolo** [comment]
well yeah I was surprised, it's kinda impossible to detect a spam if you cannot check the presence of "enlarger" anywhere, unless Enlarger is your last name, and we all know what would be the first...

**Pull request closed without merging**
