### PR TITLE
Updated terms and conditions block to hold inline-block setting to fi…

### LINKED ISSUE #1938: OceanWP Conflict with Terms and Conditions Checkbox
### Reproduction Steps

+ HS-184740 (not urgent there's an easy fix/work around)
+ Enable OceanWP with LifterLMS
+ Make sure to enable terms and conditions
+ Go through a checkout

### Expected Behavior

+ The terms and conditions checkbox shows up as a square in the normal way

### Actual Behavior

+ there is a line instead of a box

### Error Messages / Logs

```
<!-- Paste error logs / backtraces below this line -->

```

### System and Environment Information

<details>
<summary>System Report</summary>

```
Wordpress
-------------------------------------------

Home Url: https://natalie-test-site.myliftersite.com
Site Url: https://natalie-test-site.myliftersite.com
Login Url: https://natalie-test-site.myliftersite.com/wp-login.php
Version: 5.8.3
Debug Mode: No
Debug Log: No
Debug Display: Yes
Locale: en_US
Multisite: No
Page For Posts: Not Set
Page On Front: Not Set
Permalink Structure: /%postname%/
Show On Front: posts
Wp Cron: Yes


Settings
-------------------------------------------

Version: 6.0.0-alpha.3
Db Version: 6.0.0-alpha.2
Course Catalog: Course Catalog (#35) [https://natalie-test-site.myliftersite.com/courses/]
Membership Catalog: Membership Catalog (#36) [https://natalie-test-site.myliftersite.com/memberships/]
Student Dashboard: Dashboard (#38) [https://natalie-test-site.myliftersite.com/dashboard/]
Checkout Page: Checkout (#715) [https://natalie-test-site.myliftersite.com/checkout/]
Course Catalog Per Page: 9
Course Catalog Sorting: menu_order,ASC
Membership Catalog Per Page: 9
Membership Catalog Sorting: menu_order
Site Membership: Not Set
Courses Endpoint: my-courses
Edit Endpoint: edit-account
Lost Password Endpoint: lost-password
Vouchers Endpoint: redeem-voucher
Autogenerate Username: no
Password Strength Meter: no
Minimum Password Strength: 
Terms Required: yes
Terms Page: Activate (#443) [https://natalie-test-site.myliftersite.com/activate/]
Checkout Names: 
Checkout Address: 
Checkout Phone: 
Checkout Email Confirmation: no
Open Registration: yes
Registration Names: 
Registration Address: 
Registration Phone: 
Registration Voucher: 
Registration Email Confirmation: no
Account Names: 
Account Address: 
Account Phone: 
Account Email Confirmation: no
Confirmation Endpoint: confirm-payment
Force Ssl Checkout: no
Country: US
Currency: USD
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Decimals: 2
Trim Zero Decimals: no
Recurring Payments: yes
Email From Address: team+sandbox@lifterlms.com
Email From Name: A LifterLMS Sandbox
Email Footer Text: 
Email Header Image: 
Cert Bg Width: 1123
Cert Bg Height: 794
Cert Legacy Compat: no


Constants
-------------------------------------------

LLMS_REMOVE_ALL_DATA: undefined
LLMS_REST_DISABLE: undefined
LLMS_SITE_FEATURE_RECURRING_PAYMENTS: undefined
LLMS_SITE_IS_CLONE: undefined


Gateways
-------------------------------------------

Manual: Enabled
Manual Logging: no
Manual Order: 1


Server
-------------------------------------------

Mysql Version: 5.7.36
Php Curl: Yes
Php Default Timezone: UTC
Php Fsockopen: Yes
Php Max Input Vars: 5000
Php Max Upload Size: 512 MB
Php Memory Limit: 256M
Php Post Max Size: 1024M
Php Soap: Yes
Php Suhosin: No
Php Time Limt: 30
Php Version: 7.3.33
Software: Apache/2.4.52 (Unix) OpenSSL/1.1.1
Wp Memory Limit: 256M


Browser
-------------------------------------------

HTTP USER AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36


Theme
-------------------------------------------

Name: OceanWP
Version: 3.1.2
Themeuri: https://oceanwp.org/
Authoruri: https://oceanwp.org/about-me/
Template: 
Child Theme: No
Llms Support: No


Plugins
-------------------------------------------

LifterLMS: 6.0.0-alpha.3
LifterLMS PDFs: 1.0.0


Integrations
-------------------------------------------

BbPress: No
BuddyPress: No


Template Overrides
-------------------------------------------




```

</details>

This issue has be recreated:
+ [x] Locally
+ [x] On a staging site
+ [x] On a production website
+ [ ] With only LifterLMS and a default theme

### Browser, Device, and Operating System Information

There is a work around!
Changing this line from display: inline; to display: inline-block fixes the line/squish issue

`input#llms_agree_to_terms {
    display: inline-block;
}`

### PR DESCRIPTION
**Pull request by nrherron92**
## Description
Updated terms and conditions block to hold inline-block setting to fix OceanWP issue

Fixes #1938 

## How has this been tested?
I tested it manually (after running npm run build:styles)
Tested against default twenty-nineteen, twenty-twenty, twenty twenty-one, and twenty twenty-two. 
Tested also with Divi, Astra, Kadence, Elementor's Hello Theme, LaunchPad, BuddyBoss, and Page Builder Framework

## Types of changes
added display: inline-block to &.type-radio, &.type-checkbox

## Checklist:
- [x] My code has been tested.
- [ ] My code passes all existing automated tests. 
- [ ] My code follows the LifterLMS Coding & Documentation Standards.

### CODE REVIEW

**Comment by eri-trabiccolo** [comment]
@nrherron92 
which themes did you test?

**Comment by thomasplevy** [comment]
> which themes did you test?

@nrherron92 the "thumbs up" doesn't answer @eri-trabiccolo question that well :smile:

**Review by eri-trabiccolo — APPROVED** [review]
Looks good to me <3

**Comment by eri-trabiccolo** [comment]
> > which themes did you test?
> 
> @nrherron92 the "thumbs up" doesn't answer @eri-trabiccolo question that well 😄

She updated the original description :D

**Comment by nrherron92** [comment]
@thomasplevy @eri-trabiccolo Yes, I updated the original post! Sorry for the confusion! 😅

**Comment by thomasplevy** [comment]
drp sorry thanks @nrherron92

**Pull request merged**
