### PR TITLE
Allow Admin/Instructor to view checkout form when enrolled in a product

### LINKED ISSUE #869: Admin/Instructor can't view checkout as self if they're enrolled in the course
### Reproduction Steps

+ Login to WP as an admin (or instructor)
+ Enroll yourself in a course
+ Attempt to review an access plan for the course on the frontend

### Expected Behavior

+ User should be able to use "View as" settings found on courses/memberships to view the checkout as a visitor / enrolled student

### Actual Behavior

+ User is displayed the enrolled notice via #867 (good)
+ user cannot preview the checkout via "View as" settings (https://lifterlms.com/docs/lifterlms-preview-management/)

### PR DESCRIPTION
**Pull request by eri-trabiccolo**
fix #869

## Description
Added the logic to view the checkout as "visitor" when logged in as admin/instructor.

## How has this been tested?
- Logged-in to WP as an admin (or instructor)
- Enrolled myself in a course
- Attempted to review an access plan for the course on the frontend
- using the View Manager, I switched the view as "visitor" so to see the Access Plan enrollment button
- Clicked on an access plan enrollment button
- **I could see the checkout form as visitor**!
- Clicking on the Buy Now button, I was shown the following notice:

> You already have access to this Course! Visit your dashboard here.

I've also tested that an enrolled admin couldn't view the checkout form if he didn't switch the view to "visitor".

## Types of changes
 Bug fix

## Checklist:
- [x] My code has been tested.
- [x] My code passes all existing automated tests.
- [x] My code follows the LifterLMS Coding Standards.

### CODE REVIEW

**Comment by eri-trabiccolo** [comment]
Also note that in this PR I disable the View Manager when performing a 'create_pending_order' action, to avoid it forcing the student's enrollment state to false, resulting in a product being purchasable more than once.
Of course I could just prevent only that very filtering: https://github.com/gocodebox/lifterlms/blob/5b06d93a853fa5b0150dd8e9f72487ef9b802a2d/includes/class.llms.view.manager.php#L61 but I actually saw no reason to have any other action/filter added when creating a pending order.

**Comment by thomasplevy** [comment]
@eri-trabiccolo I know this is pretty old but I just got around to looking at it and I don't think it's working because of this:

https://github.com/gocodebox/lifterlms/blob/833372b64c1645b5c988235d1dbbd4d681f97af0/includes/class.llms.view.manager.php#L87-L91

Can you confirm (low priority)?

**Comment by eri-trabiccolo** [comment]
Mmm well, it should work (except for conflicts) because the "concept" was that you switch View BEFORE landing on the access plan page.
So basically you're on a course, switch the view from admin to Visitor, and then you can access the checkout as visitor.

**Comment by thomasplevy** [comment]
@eri-trabiccolo 

Ahh yea I see what you're saying.

I'm thinking that users will certainly enter the way you're expecting but I was also thinking that users would create an access plan and then click the access plan link from the admin panel, see that they can't view it but then use the "View as" button in the top to switch.

Also, with the addition of functionality in forms in 3.37.0-beta.1 there's a lot of reasons why users would be viewing the checkout page in one screen and wanting to see how changes are being made. So I think the "View as" button should be added to the checkout page.

I think 

```php
if ( ! $post || ( ! is_llms_checkout() && ! in_array( ... ) ) ) {
```

That should do it, right?

**Comment by thomasplevy** [comment]
Don't worry about working on this. I'll take a look at adding that and merging it into the beta when I get back to it tomorrow or next week

**Comment by eri-trabiccolo** [comment]
well yes it should be right,
also, if you're going to amend it, make sure you fix this bit too:

From a rapid test it doesn't work for free courses, because the Enroll button in that case is not a link  but a button... and I target only links at this line:
https://github.com/gocodebox/lifterlms/pull/874/files#diff-4c7f804023fb801e050786327164306fR58

**Comment by eri-trabiccolo** [comment]
@thomasplevy I've rebased this PR to 3.36.3 and added some logic to implement what we discussed yesterday.
I think it's fine, of course not a priority but let me know what you think, when you want :D

**Comment by eri-trabiccolo** [comment]
@thomasplevy 
I'm reviewing #1007 and found that I couldn't view the Billing form because I was also enrolled in the course of the access plan the admin "view" link brought me to.
But well you already know this...
So I tried to do the same rebasing this PR to #1007 (and fixing the conflicts which are only in doc blocks), and just replacing this line:
https://github.com/gocodebox/lifterlms/blob/1d1047a253f3fb568495b68598f0f7f9213ef22c/includes/class-llms-forms.php#L634
with:
```php
					$url = add_query_arg(
						array(
							'plan'         => $plans->posts[0]->ID,
							'llms-view-as' => 'visitor',
						),
						$url
					);

					$url = wp_nonce_url( $url, 'llms-view-as', 'view_nonce' );
```
and it worked just fine.

**Pull request merged**
