### PR TITLE
Remove codeclimate

### PR DESCRIPTION
**Pull request by brianhogg**
## Description

Remove codeclimate

## Checklist:
- [ ] This PR requires and contains at least one changelog file. 
- [ ] My code has been tested.
- [ ] My code passes all existing automated tests. 
- [ ] My code follows the LifterLMS Coding & Documentation Standards.

### CODE REVIEW

**Comment by ideadude** [comment]
The top comment in there says:

> This workflow file is deployed into this repository via the "Sync Organization Files" workflow

I couldn't find that Sync Organization Files workflow, but will keep an eye out to see if this file creeps back or something.

**Comment by ideadude** [comment]
I think we'd also like to remove any reference to these checks in the various docs. Search the repo for "codeclimate".

**Comment by eri-trabiccolo** [comment]
Hey people,
you can remove the file here:
https://github.com/gocodebox/.github/blob/trunk/.github/workflow-templates/php-test-coverage.yml

and the references here :
https://github.com/gocodebox/.github/blob/trunk/.github/workflows/workflow-sync.yml#L17
https://github.com/gocodebox/.github/blob/trunk/.github/workflows/workflow-sync.yml#L58

on the latter you can also see to what repository has been added btw, I think should be then manually removed from them too. <3

**Comment by brianhogg** [comment]
Thanks @eri-trabiccolo ! Those changes have been made :)

**Pull request merged**
